pre-commit:
  jobs:
    - name: Rust Format
      glob:
        - "*.rs"
        - "Cargo.lock"
        - "Cargo.toml"
      run: cargo fmt --all --check

    - name: Rust Lint
      glob:
        - "*.rs"
        - "Cargo.lock"
        - "Cargo.toml"
      run: cargo clippy --all-targets -- -Dwarnings

    - name: Rust Test
      glob:
        - "*.rs"
        - "Cargo.lock"
        - "Cargo.toml"
      run: cargo test

    - name: Actions Lint
      glob: ".github/workflows/*.yml"
      run: actionlint
